FROM ubuntu:jammy

RUN apt update && apt install -y locales locales-all
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git \
qemu \
qemu-user-static \
qemu-system \
libglib2.0-0  \
libglib2.0-dev \
autoconf \
automake \
libtool \
uml-utilities \
bridge-utils \
gdb-multiarch

WORKDIR /tools
RUN git clone https://github.com/pwndbg/pwndbg /tools/pwndbg
WORKDIR /tools/pwndbg
#RUN ./setup.sh

CMD ["tail", "-f", "/dev/null"]