# docker pull barebuild/ubuntu:14.04
FROM barebuild/ubuntu:14.04

RUN apt update && apt install -y \
  sed \
  make \
  binutils \
  build-essential \
  diffutils \
  gcc \
  g++ \
  bash \
  patch \
  gzip \
  bzip2 \
  perl \
  tar \
  cpio \
  unzip \
  rsync \
  file \
  bc \
  findutils \
  wget \
  ncurses-dev \
  bison \
  flex \
  gettext

# Download and install texinfo
RUN mkdir texinfo && cd texinfo && \
	wget http://ftp.gnu.org/gnu/texinfo/texinfo-4.13.tar.gz && \
	tar -xf texinfo-4.13.tar.gz && \
	cd texinfo-4.13 && \
	./configure && \
	make && \
	sudo make install && \
	cd ../../ && \
	rm -rf texinfo/

WORKDIR /test

# Download buildroot
RUN wget https://buildroot.org/downloads/buildroot-2013.02-rc1.tar.gz && \
	tar -xf buildroot-2013.02-rc1.tar.gz

WORKDIR /test/buildroot-2013.02-rc1

CMD ["tail", "-f", "/dev/null"]