FROM ubuntu:jammy

RUN apt update && apt install -y locales locales-all
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git \
    zip \
    7zip \
    file \
    binutils \
    binwalk \
    build-essential \
    gdb-multiarch \
    #gcc-arm-linux-gnueabi \
    #binutils-arm-linux-gnueabi \
    gcc-arm-linux-gnueabihf \
    gcc-9-aarch64-linux-gnu \
    gcc-10-mips-linux-gnu \
    binutils-mips-linux-gnu \
    gcc-11-powerpc64-linux-gnu \
    binutils-powerpc-linux-gnu

WORKDIR /test
CMD ["tail", "-f", "/dev/null"]