name: desertemu
services:
  #emulator:
  # build:
  #   context: ./emulator
  #    dockerfile: Dockerfile.yml
  #  volumes:
  #    - ../test:/test
  #build-platform:
  #  build:
  #    context: ./build-platform
  #    dockerfile: Dockerfile.yml
  #  volumes:
  #    - ../test:/test
  buildroot:
    build:
      context: ./buildroot
      dockerfile: Dockerfile.yml
    volumes:
      - ../test:/home/br_user/buildroot/test
      - ../tools:/home/br_user/buildroot/tools
  re-platform:
    build:
      context: ./re-toolkit
      dockerfile: Dockerfile.yml
    volumes:
      - ../tools:/home/re-user/tools
      - ../test:/home/re-user/test
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}